#include "acre_setup\root.sqf"
#include "anti_nd\root.sqf"
#include "disconnect_control\root.sqf"
#include "eg_spectator_mode\root.sqf"
#include "self_actions\root.sqf"
#include "shot_count\root.sqf"
#include "start_on_safe\root.sqf"
#include "cover_map\root.sqf"
#include "hostage_multiple\root.sqf"
#include "setup_timer\root.sqf"
#include "start_on_team_color\root.sqf"

